Handling Imbalanced Dataset
1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np 
import pandas as pd 
np.random.seed(123)

n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample*class_0_ratio)
n_class_1 = n_sample - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [4]:
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [6]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [8]:
df.tail()

     feature_1  feature_2  target
995   2.677156   1.092048       1
996   2.963404   0.181955       1
997   1.621476   1.877267       1
998   3.429559   3.794486       1
999   3.532273   1.679490       1

In [9]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [10]:
df_majority=df[df['target']==1]
df_minority=df[df['target']==0]

In [12]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority, replace=True,
         n_samples = len(df_majority),
         random_state=42
         )

In [15]:
df_minority_upsampled.shape

(100, 3)

In [16]:
df_minority_upsampled.head()

     feature_1  feature_2  target
102  -0.341700   1.173744       0
435  -0.503997   0.186730       0
860  -2.039363  -0.694636       0
270   0.395589   0.084408       0
106  -0.113904   1.281844       0

In [17]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [18]:
df_upsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64