One hot vector or nominal encoding

In [2]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [3]:
## create a simple dataframe

df = pd.DataFrame({
    'color': ['red', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1  green
2  green
3    red
4   blue

In [5]:
##create an instance of Onehotencoder
encoder=OneHotEncoder()

In [8]:
##perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [10]:
import pandas as pd 
encoder_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [ ]:
##for new data
encoder.transform([['blue']]).toarray()